docker-2 hw
Otus-DevOps-2020-05/alexbee732_microservices pull request #1
Opened 2020-08-13 19:34 UTC by alexbee732

2020-08-14 06:56 UTC, mrgreyves requested changes
Здравствуйте!) Эммм, а что вы хотели сделать этим пр?

2020-08-14 08:42 UTC, alexbee732 commented
> Здравствуйте!) Эммм, а что вы хотели сделать этим пр?

Привет) Особо ничего, просто проверил, что туда коммичу)

2020-08-14 08:59 UTC, alexbee732 commented
/fixed

2020-08-17 07:36 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2020-08-17 11:33 UTC, merged